version: "3"
services:
  client:
    image: docker-alt/client
    container_name: client
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/docker-alt/client
      - /docker-alt/client/node_modules
    command: sh "docker-entrypoint.sh"